

name: Ansible Deploy
on: 
  workflow_dispatch: 
  push: 
    branches:
      - week10



jobs:
  runs-ansible:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          ansible --version
          echo "{{ secrets.EC2_SSH_PRIVATE_KEY }}" > /tmp/key.pem
          chmod 400 /tmp/key.pem


      - name: Check Playbook (Dry Run)
        run: |
          ansible-playbook -C -vv playbook.yml

